name: adesua
region: nyc
services:
  - name: web
    github:
      repo: liamAduDonkor/adesua
      branch: master
      deploy_on_push: true
    build_command: |
      composer install --no-dev --optimize-autoloader
      npm ci
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    run_command: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=8080
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8080
    routes:
      - path: /
    health_check:
      http_path: /
    envs:
      - key: APP_NAME
        value: ADESUA
        scope: RUN_TIME
      - key: APP_ENV
        value: production
        scope: RUN_TIME
      - key: APP_KEY
        scope: RUN_TIME
        type: SECRET
      - key: APP_DEBUG
        value: "false"
        scope: RUN_TIME
      - key: APP_URL
        value: ${APP_URL}
        scope: RUN_TIME
      - key: LOG_CHANNEL
        value: stack
        scope: RUN_TIME
      - key: LOG_LEVEL
        value: error
        scope: RUN_TIME
      - key: DB_CONNECTION
        value: mysql
        scope: RUN_TIME
      - key: DB_HOST
        value: ${db.HOSTNAME}
        scope: RUN_TIME
      - key: DB_PORT
        value: ${db.PORT}
        scope: RUN_TIME
      - key: DB_DATABASE
        value: ${db.DATABASE}
        scope: RUN_TIME
      - key: DB_USERNAME
        value: ${db.USERNAME}
        scope: RUN_TIME
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
        scope: RUN_TIME
      - key: SESSION_DRIVER
        value: database
        scope: RUN_TIME
      - key: SESSION_LIFETIME
        value: "120"
        scope: RUN_TIME
      - key: CACHE_DRIVER
        value: database
        scope: RUN_TIME
      - key: QUEUE_CONNECTION
        value: database
        scope: RUN_TIME

databases:
  - name: db
    engine: MYSQL
    version: "8"
    production: true
    cluster_name: adesua-db-cluster

